# fly.toml app configuration file generated for wordsight on 2023-05-08T11:09:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wordsight"
primary_region = "nrt"

[env]
  PORT = "8000"
  SECRET_KEY = "YOU-MAKE-ME-CRAZY-209UT@GAO(IJALN)-3zo*0(zuh2w@(@%h=_qrn3c1g_=-%l897^+txfpy4=qjl@koyc"
  DEBUG = false
  DATABASE_URL = "sqlite:///db.sqlite3"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
