# Generated by Django 4.2 on 2023-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_agency',
            field=models.CharField(max_length=100),
        ),
    ]
