# Generated by Django 4.2 on 2023-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='class2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
