# Generated by Django 4.2 on 2023-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0002_alter_news_news_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='in_date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
