# Generated by Django 4.2.1 on 2023-05-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0002_alter_news_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
