# Generated by Django 4.2 on 2023-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0003_alter_keyword_in_date_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='in_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(),
        ),
    ]
